### ISSUE TITLE
Navigation timeout after login

### ISSUE THREAD

**Issue by Gians1026** [jamieweavis/dodgem#10] opened 2018-07-27 09:44 UTC
I am not really experienced on coding and I am new to this, but every time I start dodgem, it will say this (on the picture) I think it's my internet (5mbps)
![capture](https://user-images.githubusercontent.com/41718926/43314127-929c7930-91c4-11e8-96ea-4b9149f0147b.PNG)
Please tell me how to fix this, I really want to automatically bump my trades on rocket league garage

**Comment by callumthemac** [comment] 2018-07-27 09:54
How did you get my email lol? But I had this problem a couple days ago when I signed in again, you've just typed your password in wrong bud, type dodgem login again and re-enter your details, manually type your password in on RLG to make sure you're using the right one too

On 27 Jul 2018 10:44, Gians1026 <notifications@github.com> wrote:

I am not really experienced on coding and I am new to this, but every time I start dodgem, it will say this (on the picture) I think it's my internet (5mbps)
[capture]<https://user-images.githubusercontent.com/41718926/43314127-929c7930-91c4-11e8-96ea-4b9149f0147b.PNG>
Please tell me how to fix this, I really want to automatically bump my trades on rocket league garage

**Comment by callumthemac** [comment] 2018-07-27 09:56
Oh and by the way, I love this tool so please keep your knowledge of its existence to yourself, I dont want it getting widely known around the RL community as it will probably get banned and become useless

On 27 Jul 2018 10:54, Callum Macarthur <calmaca@live.com> wrote:
How did you get my email lol? But I had this problem a couple days ago when I signed in again, you've just typed your password in wrong bud, type dodgem login again and re-enter your details, manually type your password in on RLG to make sure you're using the right one too

On 27 Jul 2018 10:44, Gians1026 <notifications@github.com> wrote:

I am not really experienced on coding and I am new to this, but every time I start dodgem, it will say this (on the picture) I think it's my internet (5mbps)
[capture]<https://user-images.githubusercontent.com/41718926/43314127-929c7930-91c4-11e8-96ea-4b9149f0147b.PNG>
Please tell me how to fix this, I really want to automatically bump my trades on rocket league garage

**Comment by jamieweavis** [comment] 2018-07-27 10:00
@callumthemac you got an email about this issue because you're following the repository - looking at his screenshot it looks like he was able to login successfully but Puppeteer timed out when searching for trades.

@Gians1026 I will investigate later on today.

**Comment by callumthemac** [comment] 2018-07-27 10:44
It says you are logged in when you start dodgem even if the password is wrong haha, that's why I was so confused a few days ago, but after I logged in again with the right password it was fixed. I could be wrong and it's a completely different problem but it looks very similar to what I had

On 27 Jul 2018 11:01, Jamie <notifications@github.com> wrote:

@callumthemac<https://github.com/callumthemac> you got an email about this issue because you're following the repository - looking at his screenshot it looks like he was able to login successfully but Puppeteer timed out when searching for trades.

@Gians1026<https://github.com/Gians1026> I will investigate later on today.

**Comment by jamieweavis** [comment] 2018-07-27 12:01
@callumthemac you're right, it does say you're logged in even if you enter invalid login credentials, however the error is different to the one provided in the screenshot.

@Gians1026 is successfully logging in but timing out on the trades page, about to start investigating now.

**Comment by jamieweavis** [comment] 2018-07-27 12:16
@Gians1026 I'm unable to reproduce your problem - usually a timeout is because Rocket League Garage have changed a css selector which means Dodgem will get stuck and then eventually time out.

Could you please verify that your login credentials are correct by running `dodgem login` and then try again please?

**Comment by TheCelloFello** [comment] 2018-07-27 17:01
I've been having this issue as well. I checked that my login credentials were correct twice and the problem still occurred. Normally it would bump the trades once, and when the time interval passed it went to bump them again, but would get stuck on the "Finding active trades" and would display the UnhandledPromiseRejectionWarning.

**Comment by Gians1026** [comment] 2018-07-28 00:33
My login info is correct, I tried it 6 times by now

**Comment by Gians1026** [comment] 2018-07-28 00:36
on the screenshot, that is my 6th attempt

**Comment by Gians1026** [comment] 2018-07-28 13:08
can somebody help me please? I am waiting for a response

**Comment by jamieweavis** [comment] 2018-07-28 13:10
Could you try running Dodgem with the non-headless flag to try and see where it gets stuck? This opens a Chrome window which will show you exactly what Dodgem is doing.

```sh
dodgem start --non-headless
```

If you could attach a screenshot of where it's getting stuck then that should point me in the right direction. It's failing because it's timing out - there is a 30 second timeout duration so it should be easy to spot where it's getting stuck.

**Comment by TheCelloFello** [comment] 2018-07-29 15:39
![error](https://user-images.githubusercontent.com/41800872/43368008-d10fff92-930a-11e8-9904-02a09ae1cbf6.PNG)

There you go. It seems to be getting stuck loading the initial rocket league garage trading page.

**Comment by jamieweavis** [comment] 2018-07-29 21:52
Thanks for that @TheCelloFello.

After navigating to the `/trading` page Dodgem will attempt to navigate to your own trades `/trades/username`. But to do that it has to hover the user account in the navigation and then click My Trades.

It looks as if it's getting stuck somewhere there, I will try to investigate and fix sometime this week.

**Comment by TheCelloFello** [comment] 2018-07-29 22:04
Awesome, thanks so much for the support!

**Comment by Gians1026** [comment] 2018-07-30 01:37
Internet is broken for 1-3 days since yesterday, I went to a computer cafe just to inform you but after the 31st of July, I might not respond because I will move to my school.

**Comment by Gians1026** [comment] 2018-07-31 06:58
@TheCelloFello and I have the same problem based on his screenshot

**Comment by jamieweavis** [comment] 2018-08-02 07:59
This is really hard for me to debug since I still can't reproduce it on my machine.

I've noticed that you are both on Windows, whereas I am on macOS - maybe this could be related to the problem somehow.

I've just released `v.0.4.1` which includes upgraded dependencies, hopefully the update to Puppeteer may resolve the issue.

Could you update to the latest version and try again for me please?

**Comment by Gians1026** [comment] 2018-08-03 12:48
The problem is still the same even in the updated version

**Comment by jamieweavis** [comment] 2018-08-07 07:43
That's quite possible @callumthemac.

Has anyone been able to run Dodgem successfully yet?

**Comment by KelvinBlueberry** [comment] 2018-08-14 01:39
I have tried numerous times and have yet to figure out why it's not working. sometimes it fails to login and other times it fails to bump but whenever it fails the messages shows up.

**Comment by Ketn** [comment] 2018-08-14 22:10
@jamieweavis - the error is due to the "Too many users" error that started appearing recently. Can we do something like, if that error is detected, it will just reload the page and try the action it was supposed to, again?

**Comment by cikal** [comment] 2018-09-06 18:09
@jamieweavis , is it possible that the nodejs version has an effect so that it causes errors ?

**Comment by jamieweavis** [comment] 2018-10-18 18:05
Sorry all for the delay, haven't had much time to work on this recently.

I'm going to close this guys, thanks for all of your input. As mentioned by @Ketn this is a problem with RLG, not Dodgem - hopefully they have resolved this issue by now.

If you are using a version of Node.js higher than `7.6.x` then you should be fine @cikal.

**Closed by jamieweavis** 2018-10-18 18:05 UTC
